In [4]:
import numpy as np

In [36]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)
print(data)

[[35 23 94  6 87]
 [93 29 51  1 76]
 [97 35 80 30 92]
 [54 41 46 67 60]
 [57 21 56 18 25]]


1. Matrix manipulation - Swap the second and fourth rows of the data matrix.

In [37]:
data[[1, 3]] = data[[3, 1]]
print(data)

[[35 23 94  6 87]
 [54 41 46 67 60]
 [97 35 80 30 92]
 [93 29 51  1 76]
 [57 21 56 18 25]]


2. Normalization- Normalize all the elements in the data matrix. In this context, normalizing means to scale the values in such a way that they fall within the range of 0 and 1. To achieve this, subtract the minimum value from each element and divide by the range (max-min).

In [38]:
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized_data)

[[0.35416667 0.22916667 0.96875    0.05208333 0.89583333]
 [0.55208333 0.41666667 0.46875    0.6875     0.61458333]
 [1.         0.35416667 0.82291667 0.30208333 0.94791667]
 [0.95833333 0.29166667 0.52083333 0.         0.78125   ]
 [0.58333333 0.20833333 0.57291667 0.17708333 0.25      ]]


3. Z-score normalization - Standardize the elements in the data matrix using Z-score normalization. In this method, all the elements will be rescaled to have a mean of 0 and a standard deviation of 1. The formula for Z-score normalization is
(X - mean) / std , where ( X ) is the element in the data matrix.

In [39]:
z_score_data = (data - np.mean(data)) / np.std(data)
print(z_score_data)

[[-5.62656454e-01 -9.85706419e-01  1.51733921e+00 -1.58502720e+00
   1.27056006e+00]
 [ 1.07172658e-01 -3.51131471e-01 -1.74860652e-01  5.65476787e-01
   3.18697641e-01]
 [ 1.62310170e+00 -5.62656454e-01  1.02378092e+00 -7.38927273e-01
   1.44683088e+00]
 [ 1.48208505e+00 -7.74181436e-01  1.41016655e-03 -1.76129802e+00
   8.82764261e-01]
 [ 2.12935149e-01 -1.05621475e+00  1.77680985e-01 -1.16197724e+00
  -9.15198092e-01]]


4. Array splitting - Reshape the data matrix into a vector (Hint: use np.ravel) and split this array into five equal-sized sub-arrays.

In [41]:
vector_data = np.ravel(data)
sub_arrays = np.split(vector_data, 5)
print(sub_arrays)

[array([35, 23, 94,  6, 87]), array([54, 41, 46, 67, 60]), array([97, 35, 80, 30, 92]), array([93, 29, 51,  1, 76]), array([57, 21, 56, 18, 25])]


5. Dot product - Create two vectors of size 5 with any values. Compute the dot product of thetwo vectors*.

In [68]:
data1 = np.array([3, 5, 6, 7, 8])
vector_a = np.ravel(data1)
data2 = np.array([2, 4, 6, 8, 10])
vector_b = np.ravel(data2)
print(vector_a)
print(vector_b)

[3 5 6 7 8]
[ 2  4  6  8 10]


In [69]:
dot_product  =  np.dot(vector_a, vector_b)
print(dot_product)

198


6. Matrix multiplication - Create another 3x3 matrix with any values (let’s call it data3). Perform matrix multiplication (dot product of data (first 3x3 part) and data3).

In [83]:
data3 = np.arange(1, 10).reshape(3, 3)
print(data3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
multiplication_result = np.matmul(data[:3, :3], data3)
print(multiplication_result)

[[ 785  937 1089]
 [ 540  681  822]
 [ 797 1009 1221]]


7. Inverse of a matrix - Create a 3x3 identity matrix*, multiply it with 2 and compute its inverse.

In [51]:
from numpy.linalg import inv

In [74]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [75]:
mult_x2 = matrix * 2
print(mult_x2)

inverse = inv(mult_x2)  
print(inverse)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


8. Eigenvalues and eigenvectors - For the first 3x3 part of the data matrix, compute the eigenvalues and eigenvectors*.

In [76]:
from numpy import linalg as la

In [82]:
eigenvalues, eigenvectors = la.eig(data[:3, :3])
print(eigenvalues)
print(eigenvectors)

[176.8880524  -39.92674615  19.03869375]
[[-0.54195786 -0.78960396  0.22141386]
 [-0.45463373  0.19644745 -0.95525218]
 [-0.7068167   0.5813209   0.19613559]]


9. Find missing values - Replace random 5 elements in the data matrix with np.nan. Find the indices of the missing values.

In [86]:
data_matrix = np.random.randint(0, 100, size=(5, 5)).astype(float)

In [87]:
missing_indices = np.random.randint(0, 5, size=(5, 2))

In [88]:
for i, j in missing_indices:
    if i < 5 and j < 5:  
        data_matrix[i, j] = np.nan

10. Replace missing values - Replace the missing values in the data matrix with the mean of the matrix (ignoring the missing values while computing the mean).

In [89]:
mean_val = np.nanmean(data_matrix)

In [90]:
data_matrix[np.isnan(data_matrix)] = mean_val

In [91]:
print(data_matrix)

[[50.         95.         29.         51.76190476 56.        ]
 [49.         64.         23.         64.         27.        ]
 [59.         32.         72.         54.         51.76190476]
 [51.76190476 15.         11.         87.         94.        ]
 [67.         51.76190476 21.         65.         53.        ]]
