Exercise 1:

Instructions

1. Import the numpy package under the name np.

In [1]:
import numpy as np

2. Create a vector* of zeros with size 10 using np.zeros().

In [15]:
zero_vector = np.zeros(10)
print(zero_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Compute the memory size* of any array. Note: You can do this by multiplying the length of the array by the size of one array element, which you can find using the .itemsize attribute.

In [17]:
item_size = zero_vector.itemsize * zero_vector.size
print(item_size)

80


4. Retrieve the documentation of the numpy add function from the command line.

In [18]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

5. Create a vector with values ranging from 10 to 49 using np.arange().

In [19]:
range_10_49 = np.arange(10, 50)
print(range_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


6. Reverse a vector so the first element becomes last (Hint: Use slicing).

In [20]:
range_10_49 = range_10_49[::-1]
print(range_10_49)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


7. Create a 3x3 matrix* with values ranging from 0 to 8 using np.reshape().

In [26]:
range_3x3 = np.arange(9).reshape(3, 3)
print(range_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


8. Find indices of non-zero elements from [1,2,0,0,4,0] using np.nonzero().

In [28]:
array = [1,2,0,0,4,0]
non_zero = np.nonzero(array)
print(non_zero)

(array([0, 1, 4], dtype=int64),)


9. Create a 3x3 identity matrix* using np.eye().s

In [29]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


10. Create a 5x5 matrix with row values ranging from 0 to 4. The output should be a matrix where each row is [0, 1, 2, 3, 4].

In [41]:
row_5x5 = np.zeros((5,5))
row_5x5 += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


11. Create a vector of size 10 with values ranging from 0 to 1, both excluded. You can use np.linspace.

In [48]:
array_evenspace = np.linspace(0, 1, 12)[1:-1]
print(array_evenspace)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


12. Create a random vector of size 10 and sort it.

In [33]:
random_array = np.array(np.random.randint(1, 100, size=10))
sorted_random_array = np.sort(random_array)
print(sorted_random_array)

[ 2  8 18 23 25 45 50 57 82 97]


13. Print the minimum and maximum representable value for each numpy scalar type* (int8, int32, int64, float32, float64). Use np.iinfo and np.finfo.

In [57]:
int8 = np.iinfo(np.int8)
print(int8.min)
print(int8.max)
int32 = np.iinfo(np.int32)
print(int32.min)
print(int32.max)
int64 = np.iinfo(np.int64)
print(int64.min)
print(int64.max)
float32 = np.finfo(np.float32)
print(float32.min)
print(float32.max)
float64 = np.finfo(np.float64)
print(float64.min)
print(float64.max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


14. How to convert a float (32 bits) array into an integer (32 bits) in place? Use np.ndarray.astype.

In [65]:
type_change = np.array([1.0, 2.5, 3.0], dtype = float32)
print(type_change.dtype)

dtype('float32')

In [66]:
type_changed = type_change.astype(int32)
print(type_changed)

[1 2 3]


15. Subtract the mean* of each row of a matrix. Use np.mean with axis=1.

In [73]:
matrix = np.array([[80, 70, 90], [10, 30, 20], [110, 100, 120], [40, 60, 50]])
print(matrix)

[[ 80  70  90]
 [ 10  30  20]
 [110 100 120]
 [ 40  60  50]]


In [74]:
mean_subtracted = matrix - matrix.mean(axis=1, keepdims=True)
print(mean_subtracted)

[[  0. -10.  10.]
 [-10.  10.   0.]
 [  0. -10.  10.]
 [-10.  10.   0.]]


16. How to sort an array by the nth column? Use np.argsort.

In [75]:
sorted_matrix = matrix[matrix[:,-1].argsort()]
print(sorted_matrix)

[[ 10  30  20]
 [ 40  60  50]
 [ 80  70  90]
 [110 100 120]]


17. How to swap two rows of an array? You can do this using array indexing.

In [76]:
matrix[[0, 2]] = matrix[[2, 0]]
print(matrix)

[[110 100 120]
 [ 10  30  20]
 [ 80  70  90]
 [ 40  60  50]]


18. Given an array C that is a bincount*, how to produce an array A such that np.bincount(A) == C? Use np.repeat.

In [78]:
array1  = [2, 2, 1, 1, 1, 0, 0, 0, 3, 3]

In [79]:
c = np.bincount(array1)
print(c)

[3 3 2 2]


In [81]:
a = np.repeat(np.arange(len(c)), c)
print(a)

[0 0 0 1 1 1 2 2 3 3]
